### ISSUE TITLE
BEP 27 - Private Torrents

### ISSUE THREAD

**Issue by benjamintillman** [atomashpolskiy/bt#1]
Just taking up the invite to 'vote' for a new BEP to be implemented, per README.md 😄 

See http://www.bittorrent.org/beps/bep_0027.html

**Comment by atomashpolskiy** [comment]
@benjamintillman , sure, this should not be very difficult to implement. Would you mind sharing what your use case is? I'm genuinely interested in how folks use Bt (and you happened to be the first one to show up :)

**Comment by benjamintillman** [comment]
Hi @atomashpolskiy, a lot of bittorrent trackers I use are ... 'private' in nature, all of whom require the use of private torrents. I don't currently use Bt, but this BEP being implemented will allow me to start playing around using my existing trackers, and I had the idea to maybe try and embed Undertow (for example) and write a simple web based UI.

**Comment by atomashpolskiy** [comment]
@benjamintillman , I've just commited the update for BEP-27 support.

I should say that the whole concept of private torrents seems kind of orthogonal to the nature of BitTorrent, esp. in regards to separating users of different trackers into separate swarms. So, while it's perfectly clear why the client should disconnect from all connected peers when switching trackers, it's still a bit of a pain in the ass to do this in the code. At least I haven't been able to figure out a reasonable way of doing it yet.

As a temporary workaround, for now the client will not be able to utilize multi-trackers (BEP-12) when working with private torrents. It should not be a big problem though, as it is guaranteed that a metainfo file always has the standard `announce` property.
