### ISSUE TITLE
yourIp example doesn't work in latest releases

### ISSUE THREAD

**Issue by sazonenko** [atomashpolskiy/bt#100]
I'm check out latest version and trying to run YourIp example, but it doesn't seems to work. So I check out version 1.6 and it do nothing. The only version that works for me is 1.5 .
After some debugging I figured out that method 
```
    @Consumes
    public void consume(ExtendedHandshake handshake, MessageContext context) {

```
is never called. So, messenger can't populate it's "supportingPeers" collection. But, I don't understand how to fix it. Please, help

**Comment by sazonenko** [comment]
finally, I can figure it out. When more than one module have consumers for one type of message then only one can receive them. The reason of this :
https://github.com/atomashpolskiy/bt/blob/33f639202a700451ebff0a883806a320e8e29013/bt-core/src/main/java/bt/torrent/messaging/DefaultMessageRouter.java#L98
This code replaces all keys in the map with new one.
I can fix it like this:

```
typedMessageConsumers.keySet().forEach(key -> {
    this.typedConsumers.computeIfAbsent(key, k -> new ArrayList<>()).addAll(typedMessageConsumers.get(key));
});
```

**Comment by atomashpolskiy** [comment]
You're right, thank you very much for taking the time to figure this out! Would you be able to make a PR?
