### ISSUE TITLE
HTTP tracker support

### ISSUE THREAD

**Issue by JustAGod1** [atomashpolskiy/bt#104]
Описание протокола HTTP трекера с офф. сайта bit torrent:
`Tracker responses are bencoded dictionaries. If a tracker response has a key failure reason, then that maps to a human readable string which explains why the query failed, and no other keys are required. Otherwise, it must have two keys: interval, which maps to the number of seconds the downloader should wait between regular rerequests, and peers. peers maps to a list of dictionaries corresponding to peers, each of which contains the keys peer id, ip, and port, which map to the peer's self-selected ID, IP address or dns name as a string, and port number, respectively. Note that downloaders may rerequest on nonscheduled times if an event happens or they need more peers.`
[Сайт](http://bittorrent.org/beps/bep_0003.html)
В вашей же библиотеке для парсинга ответа HTTP трекера используется такой же код как и в UDP протоколе.

**Comment by atomashpolskiy** [comment]
Вы ошибаетесь. Смотреть можно сюда: https://github.com/atomashpolskiy/bt/blob/3cde897bf959d68958ec44277e2d134bfe51be3a/bt-http-tracker-client/src/main/java/bt/tracker/http/HttpTracker.java#L144-L150
И сюда:
https://github.com/atomashpolskiy/bt/blob/3cde897bf959d68958ec44277e2d134bfe51be3a/bt-http-tracker-client/src/main/java/bt/tracker/http/HttpResponseHandler.java#L118

**Comment by JustAGod1** [comment]
Я смотрю вот [сюда](https://github.com/atomashpolskiy/bt/blob/dc974ec48e5b042d1892916d4aabadfc1e0cdd56/bt-http-tracker-client/src/main/java/bt/tracker/http/HttpResponseHandler.java#L160)
Может я конечно что то не так понял, но кажется по протоколу предполагается, что там будет лист словарей, а вы зачем то кастите это к массиву байтов.

**Comment by atomashpolskiy** [comment]
Да, потому что есть вот такая спека на этот счет:
http://bittorrent.org/beps/bep_0023.html
Все общеиспользуемые трекеры работают по ней, а не по BEP-3
