### ISSUE TITLE
Invalid MagentLink Parsing

### ISSUE THREAD

**Issue by phillui-37** [atomashpolskiy/bt#105]
## Issue
For this magnet link: `magnet:?xt=urn:btih:JVZCIO55JGW5Q76YQE54A2XCPQ3YA2CK&dn=`
Bt.client().magent(...) will fail directly

## Log
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at bt.magnet.MagnetUriParser.collectParams(MagnetUriParser.java:150)
	at bt.magnet.MagnetUriParser.parse(MagnetUriParser.java:111)
	at bt.magnet.MagnetUriParser.parse(MagnetUriParser.java:92)
	at bt.TorrentClientBuilder.magnet(TorrentClientBuilder.java:121)
	at Main$.main(Main.scala:20)
	at Main.main(Main.scala)
```

## Possible Fix Sol.
**bt-core/bt/magnet/MagnetUriParser.java** Line 147-157
```java
for (String param : params) {
            String[] parts = param.split("=");
            // ADDED HERE
            if (parts.length == 1) {
                continue;
            }
            // ADDED FINISHED
            String name = parts[0];
            String value = parts[1];
            List<String> values = paramsMap.get(name);
            if (values == null) {
                values = new ArrayList<>();
                paramsMap.put(name, values);
            }
            values.add(value);
        }
```

or shall I make a PR?

**Comment by atomashpolskiy** [comment]
According to http://bittorrent.org/beps/bep_0009.html `dn` stands for
Display Name. In your case it's empty, which is probably an error. With
your proposed fix we'll allow any parameters to be absent, and this might
lead to even more confusion. What I'd do is explicitly check if the value
is present and if not, throw an IllegalArgumentException with a descriptive
message...

**Comment by phillui-37** [comment]
Thanks. Your concern is right, I will handle magnet link before pass to client.

One more thing but not related to issue stated here, this magnet link info hash is base32 encoded, will you concern to support base32 info hash in the future?

**Comment by atomashpolskiy** [comment]
Sorry for the late response! That would certainly be nice
