### ISSUE TITLE
Why is the video file I downloaded prompts corrupt and cannot be played?

### ISSUE THREAD

**Issue by ghost** [atomashpolskiy/bt#123]
I thought it was a problem with the source file. The result is that the same file can be downloaded normally with BitComet.

**Comment by atomashpolskiy** [comment]
Please specify the version that you're using and provide the torrent file
or a magnet link, so that I could reproduce the issue.

**Comment by zhangxiao4552** [comment]
My Version:1.8
magnetUri: magnet:?xt=urn:btih:dbc97be40b44f0b518e4757ef644ee9da3ba8944

**Comment by atomashpolskiy** [comment]
Explicit content there. Closed.
