### ISSUE TITLE
Utp protocol?

### ISSUE THREAD

**Issue by master255** [atomashpolskiy/bt#141]
What about the Utp protocol? Does the library only use TCP? Utp no?
If it exists, then give a link to the implementation?

**Comment by atomashpolskiy** [comment]
Yes, message exchange between peers is done via plain TCP.

**Comment by master255** [comment]
@atomashpolskiy Does this mean that the library does not support peers that can only connect via Udp?

**Comment by atomashpolskiy** [comment]
Yes

**Comment by master255** [comment]
@atomashpolskiy I found two implementations of the Utp protocol in Java. We can see what's wrong with them together and fix the problems. To use this.
1. https://github.com/iiljkic/utp4j/issues/2
2. https://git.johnnei.org/Johnnei/JavaTorrent/tree/develop/bittorrent-utp

All I need is the Utp protocol for my library, the rest is there.

**Comment by master255** [comment]
I am also trying to add c++ libraries to the project. But this is a very difficult way.

**Comment by master255** [comment]
@atomashpolskiy Now I'm trying to use the second library. You can see what's wrong with the first library. It gets the first data, but next nothing happens.

**Comment by atomashpolskiy** [comment]
I checked both of these libraries at some point, and they did not seem to
work properly. In any case, why do you think you need uTP? It's an
overengineered thing, and it's known to cause traffic bloat, which led many
ISPs to block it completely (e.g. on rutracker.org one of the common
advices for not getting connections is to disable uTP).

**Comment by master255** [comment]
@atomashpolskiy Because most torrent peers run on a Utorrent client. And it has priority for the utp protocol. They don't respond to TCP connections, but they do respond to Utp. If we can use the Utp protocol, then the peers for downloading data will be much more.

You can test it with any Utorrent client. Even libtorrent (there is a Java adapter) uses mostly Utp. But there it is called Socks5 over UDP.

**Comment by atomashpolskiy** [comment]
Where do you get this information? As far as I known, there is no (and
should not be any) bias towards either of the transports. I.e. both TCP and
uTP incoming connections should be accepted, unless the user has changed
the default settings.

**Comment by master255** [comment]
@atomashpolskiy What about the incoming connections? Utorrent sends TCP and UTP requests alternately to the connection and with a delay of about one minute.
If the Utorrent client sends the first request to your library via the UTP protocol, and you ignore it, you have to wait about a minute to get the incoming TCP request. Sometimes intervals are longer than a minute.
So, you have 50% of all possible peers and maybe (if you create a new thread, for each incoming connection, and your library doesn't have it) in a minute another 10-20%, but not 100%.
This slows down the download very much.

**Comment by atomashpolskiy** [comment]
I don't argue that we miss some peers and maybe experience decreased rates
by not supporting uTP, that's a fact. But that becomes a problem only when
the cumulative bandwidth of the swarm (or rather our share in it) is small.
This is an edge case by all standards. I would be happy to support it, but
not going to invest time into implementing uTP properly, and existing Java
implementations don't look promising. Fitting it into the existing
messaging model might also be difficult without refactoring. Overall, I
think that this effort is not really justified.

**Comment by master255** [comment]
@atomashpolskiy I'm checking the trick now. If all incoming Utp connections are forced to close and try to connect to them via TCP. This will make it easier to implement Utp.
I'll text you when I'm done.

**Comment by atomashpolskiy** [comment]
On a side note. Java BitTorrent libraries are not in a big demand for
building your run-of-the-mill torrent clients for desktops and smartphones,
because of the stigma of the Java language and its' objective drawbacks
like JVM startup times. Both Bt and Ttorrent are used in totally different
environments, like CI systems, IP fraud detection crawlers, software
delivery systems, etc. All of these environments are homogenous, in the
sense that all nodes use exactly the same BitTorrent implementation. So the
issues of compatibility or support for obscure features is basically
non-existent.

**Comment by master255** [comment]
@atomashpolskiy Yes! I was able to trick the Udp connection. 
When an incoming Udp connection is received, I do not close it, but just create a new TCP connection at this address and get the data without delay!
Logs:
2020-04-01 21:25:31.731 31910-32053/com.media.library D/httpPlayer: income utp: BitTorrent protocol������������åUÓi9_s æ"¤3Ù-UT2210-bó%Î«<ýÐx
2020-04-01 21:25:31.743 31910-32053/com.media.library D/httpPlayer: connected to:192.168.1.100:53865 working:false busy:true
2020-04-01 21:25:31.850 31910-32053/com.media.library D/httpPlayer: get response:BitTorrent protocol������������åUÓi9_s æ"¤3Ù-UT2210-bó%Î«<ýÐx������_ÿÿ¿ÿÿýÿÿÿÿýÿßÿÿÿÿÿÿÿÿÿÿßÿ÷þÿÿÿÿÿÿýÿïÿÿÿïÿý¿ÿÿïÿÿýÿÿÿßÿÿÿÿÿÿÿÿÿÿÿ÷ÿïÿÿ÷ÿÿÿÿÿÿÿÿÿÿÿÿÿÿïÿ÷¿ÿßÿà����������V����������C���������� ����������Ú������������^����������#��������������������ª��������������������³������������6����������<������������j������������Ô������������ß����������s����������É����������Y������������������������Â��������������������������������(����������Ä
2020-04-01 21:25:31.864 31910-32053/com.media.library D/httpPlayer: income connection work! 192.168.1.100:53865 working:true busy:false

**Comment by master255** [comment]
@atomashpolskiy Another question: how do I keep dht and Utp on the same port?

**Comment by atomashpolskiy** [comment]
You can't have two sockets bound to a single port.

**Comment by master255** [comment]
@atomashpolskiy I know. DHT works without port forwarding. But when searching through the DHT, peers are trying to connect to me through this port that I use in the DHT.
Are DHT and UTP using the same UDP port or different?

**Comment by atomashpolskiy** [comment]
Not sure I understand the question. DHT default is 49001, you may see the
default values in Config class.

**Comment by master255** [comment]
@atomashpolskiy Yes, it's one port. https://github.com/arvidn/libtorrent/issues/4493

**Comment by atomashpolskiy** [comment]
Then you need to bind your uTP socket to a different port and announce it
in the extended handshake message, because DHT library already uses a
socket exclusively for DHT messages.

**Comment by master255** [comment]
@atomashpolskiy No! DHT and UTP use the same port to receive and transmit messages. In this case, incoming traffic is filtered to UTP and DHT and distributed to the appropriate modules. During the search in DHT on the port which uses DHT incoming UTP connections are received, and through one port works both search and data transfer simultaneously! This is difficult, but possible.
This is the most commonly used scenario for downloading torrents.

**Comment by master255** [comment]
@atomashpolskiy https://github.com/arvidn/libtorrent/issues/4493 just read

**Comment by atomashpolskiy** [comment]
I understand that a single UDP socket can be used for multiplexing multiple message streams. But the8472/mldht does not support this as far as I'm aware.

**Comment by master255** [comment]
@atomashpolskiy That's why I make my DHT module. As it turned out, it's not difficult.
I'm already getting peers from the DHT and can add packet distribution logic.

**Comment by master255** [comment]
@atomashpolskiy A block of work code. Separation of incoming packets.
```
@Override
    public void recievePacket(DatagramPacket packet) {
        if (packet.getData()[0] == 100 && packet.getData()[packet.getLength() - 1] == 101)
            dhtModule.receivePacket(packet);
        else if (UtpPacketUtils.isSynPkt(packet)) {
            synRecieved(packet);
        } else {
            UtpPacket utpPacket = UtpPacketUtils.extractUtpPacket(packet);
            ConnectionIdTriplet triplet = connectionIds.get(utpPacket.getConnectionId() & 0xFFFF);
            if (triplet != null) {
                triplet.getChannel().recievePacket(packet);
            }
        }
    }
```

**Comment by master255** [comment]
@atomashpolskiy Now I'm going to figure out why the Utp protocol doesn't work. Maybe I'm sending the wrong HandShake.

**Comment by master255** [comment]
@atomashpolskiy I win utp! The data is coming. Handshake is successfully passing. Now I' m doing architectural optimizations. Conversion from Java beginner language to Java professional.
