### ISSUE TITLE
Can't import the dependencies

### ISSUE THREAD

**Issue by Seanmusse** [atomashpolskiy/bt#143]
Hello! 
I've tried importing the dependencies by pasting the code on the home page of this github repo to my pom.xml but for some reason it doesn't work. I'm using IntelliJ IDEA and on the first dependency tag it highlights it as wrong and it just doesn't work. Here is the error I get: 

```
Cannot resolve com.github.atomashpolskiy:bt-core:${bt-version}

Cannot resolve com.github.atomashpolskiy:bt-dht:${bt-version}

Cannot resolve com.github.atomashpolskiy:bt-upnp:${bt-version}

Cannot resolve com.github.atomashpolskiy:bt-http-tracker-client:${bt-version}

```
And here is my pom.xml file (just a brand new one with the dependencies pasted in): 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>btTest</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.github.atomashpolskiy</groupId>
            <artifactId>bt-core</artifactId>
            <version>${bt-version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.atomashpolskiy</groupId>
            <artifactId>bt-http-tracker-client</artifactId>
            <version>${bt-version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.atomashpolskiy</groupId>
            <artifactId>bt-dht</artifactId>
            <version>${bt-version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.atomashpolskiy</groupId>
            <artifactId>bt-upnp</artifactId>
            <version>${bt-version}</version>
        </dependency>
    </dependencies>
</project>

```
I've also tried building it from source and then adding bt-core as an external library on my project, but it didn't seem to work as well. 
I think it's obvious but I'm a beginner and have never used maven before. 

Maven seems to be working fine, building it from source gave me no problems and running `mvn --version` also outputs a valid result. 

Any suggestions are welcome!

**Comment by atomashpolskiy** [comment]
You should specify a specific version to be imported, e.g. 1.9

${property} is Maven's syntax for interpolation. If you are a beginner,
then you may just remove it and replace with the version number.

**Comment by Seanmusse** [comment]
If I understood correctly, you wanted me to replace every ${bt-version} with ${1.9}. After doing so I got this error: 

```
Cannot resolve com.github.atomashpolskiy:bt-http-tracker-client:${1.9}

Cannot resolve com.github.atomashpolskiy:bt-core:${1.9}

Cannot resolve com.github.atomashpolskiy:bt-upnp:${1.9}

Cannot resolve com.github.atomashpolskiy:bt-dht:${1.9}

```

I appreciate your speedy response by the way, thank you!

**Comment by atomashpolskiy** [comment]
No, just 1.9, without the dollar sign and curly brackets. You are welcome.

**Comment by Seanmusse** [comment]
I realized how dumb that was the second after I commented, I was supposed to just replace ${1.9} for 1.9... Worked perfectly, sorry for the dumb mistake and thank you once more!
