### ISSUE TITLE
sessionState.getDownloaded() value exceeds the size of the torrent to be downloaded.

### ISSUE THREAD

**Issue by Dhina17** [atomashpolskiy/bt#148]
```
public static void main(String[] args){
        Storage out = new FileSystemStorage(new File("."));
        BtClient client = Bt.client().storage(out)
                                .magnet("Here magnet link")
                                .afterTorrentFetched(Test::setTorrent)
                                .build();

        client.startAsync(state -> {
            
                if (state.getPiecesRemaining() == 0) {
                    System.out.println("Completed");
                        client.stop();
                }
                if(torrent1 != null){
                    System.out.println(torrent1.getName());
                    System.out.println(state.getDownloaded() + "/" + torrent1.getSize());
                }
        }, 1000);
```
Here is my code. getDownloaded exceeds the total size of the torrent. May be something I missed.

**Comment by atomashpolskiy** [comment]
It's fine. Some pieces were downloaded more than once probably.

**Comment by Dhina17** [comment]
Any work around for that issue?

**Comment by atomashpolskiy** [comment]
It is not an issue, but by protocol's design. What problem are you trying
to solve?

**Comment by Dhina17** [comment]
I want to get the correct downloaded value for a torrent.

**Comment by Dhina17** [comment]
In case , file size() of the torrent is 6000000 bytes, getDownloaded() should not return more than the file size(). 
I have this code in a static method. So new client object will be create and download only the passing magnet link then client should  be destroyed. In that case, getDownloaded() should return acceptable value(or correct value less than or equal filesize) . I don't know my client setup is good or not. Please Help me to overcome this with proper setup of the client.

**Comment by atomashpolskiy** [comment]
Once again, this is by design. See BEP-3 for the clues, why the total
amount of data downloaded will almost always be larger than the size of the
torrent being downloaded.

**Comment by Dhina17** [comment]
I will check. Thanks
