### ISSUE TITLE
why InetPeerAddress not extends InetSocketAddress ?

### ISSUE THREAD

**Issue by RumoEL** [atomashpolskiy/bt#149]
Why does InetPeerAddress not extend from InetSocketAddress if it only extends it?

**Comment by yjs112233** [comment]
Hi, RumoEL. I am also one of the BT library researchers. I have a question, but the community is not very active, Can I ask you directly? 
    Before today, I had built and used BitTorrent. However, I found that after downloading a seed whith , I could not download it again in the same BtRuntime container,  It will be thrown "Torrent already registered and data descriptor created:  xxxx.. " from 
the AdhocTorrentRegistry.class, and the download will abort,  Unless you create a new BtRunning and run it in it. 
    So. Do you know how to run the same resources in the same BtRunning? Thanks very much !

**Comment by RumoEL** [comment]
@yjs112233 Unfortunately, I don't know the solution

**Comment by atomashpolskiy** [comment]
Hey!

@yjs112233 , check out https://github.com/atomashpolskiy/bt/issues/146

@RumoEL , why are you asking?
