### ISSUE TITLE
Private Tracker - Unsupported/inactive torrent requested

### ISSUE THREAD

**Issue by otaviodecampos** [atomashpolskiy/bt#15]
I am trying to download a torrent with private tracker. I'm getting this error on bt-cli:

```
Exception in thread "bt.net.pool.connection-worker-4" java.lang.IllegalStateException: Unsupported/inactive torrent requested
        at bt.net.MSEHandshakeProcessor.negotiateIncoming(MSEHandshakeProcessor.java:361)
        at bt.net.PeerConnectionFactory.createConnection(PeerConnectionFactory.java:73)
        at bt.net.PeerConnectionFactory.createIncomingConnection(PeerConnectionFactory.java:57)
        at bt.net.PeerConnectionPool.lambda$acceptIncomingConnection$63(PeerConnectionPool.java:347)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

The file bt.log has:
`WARN  DefaultTorrentDescriptor: Tracker URL protocol is not supported: https://..tracker../announce.php?passkey=XXXX`

What could be happening?
Thanks

**Comment by atomashpolskiy** [comment]
HTTPS trackers are indeed not supported. It should not prevent the torrent session from starting though, as there may be other sources of peers (DHT in case of bt-cli).
Is the MSE negotiation error happening for all peers? Is it reproducible if you start another instance of bt-cli?
Also try disabling encryption and see whether the error goes away.

**Comment by atomashpolskiy** [comment]
In fact everything except the tracker is disabled for private torrents. Where does the incoming connection come from then? I wonder if there are back-up trackers in the torrent file?

**Comment by otaviodecampos** [comment]
Thanks for the quick response.
I can download public trackers, but in case the private tracker with HTTPS protocol does not. Because it is a private tracker, DHT is probably not going to help. (I'm not a torrent expert)

But I downloaded the project, and changed protocol key on this class

```
public class HttpTrackerModule implements Module {

    @Override
    public void configure(Binder binder) {
        ServiceModule.contributeTrackerFactory(binder).addBinding("https").to(HttpTrackerFactory.class);
    }
}

```

After that I was able to download my private tracker. I ask, is this solution valid?

Enjoying .. I really liked the project and the asynchronous footprint, Congratulations and thank you.

**Comment by otaviodecampos** [comment]
> In fact everything except the tracker is disabled for private torrents. Where does the incoming connection come from then? I wonder if there are back-up trackers in the torrent file?
Probably not. In this case the torrents only have the private tracker.

**Comment by atomashpolskiy** [comment]
If changing the binding worked for you, then it's probably valid, at least in some cases :) make sure to keep the old binding as well so that plain http continues to work
Thanks for feedback, I really appreciate it!

**Comment by otaviodecampos** [comment]
Of course. Thanks. What do you think if I open a pull request in future to register the key https for HttpTrackerModule?

**Comment by atomashpolskiy** [comment]
Sure, let's do it

**Comment by atomashpolskiy** [comment]
@otaviodecampos , hi! wanted to check with you if you'd still like to make a PR, as I'm going to make a release soon and would like to include this fix
