### ISSUE TITLE
[Question][Peer info]

### ISSUE THREAD

**Issue by RumoEL** [atomashpolskiy/bt#151]
Is it possible to get the client version and peer hashid of the remote peer?

**Comment by atomashpolskiy** [comment]
Please see https://github.com/atomashpolskiy/bt/blob/087f6c8031d9f87644bdbb964c20cdc925eb533d/bt-core/src/main/java/bt/net/IncomingHandshakeHandler.java
Note that the constructor receives a collection of `HandshakeHandler`

You should register your custom handler via https://github.com/atomashpolskiy/bt/blob/087f6c8031d9f87644bdbb964c20cdc925eb533d/bt-core/src/main/java/bt/module/ProtocolModuleExtender.java
See example in https://github.com/atomashpolskiy/bt/blob/master/bt-core/src/main/java/bt/module/ProtocolModule.java#L118

So you should add a custom Module and have something like `ProtocolModule.extend(binder).addHandshakeHandler(...)` in there

**Comment by RumoEL** [comment]
Thank you, I'll see later.
