### ISSUE TITLE
[Discussion] FileDownloadCompleteCallback may return inCompleted file

### ISSUE THREAD

**Issue by a8156268** [atomashpolskiy/bt#178]
`CompletableTorrentFile.java` using a `AtomicLong` to track chunks count. 
But in some concurrent case, `AtomicLong` may be decrement twice by the same chunk. At this time, file is incompleted.

Why not track chunks count using a set of piece indexes?

**Comment by atomashpolskiy** [comment]
CompletableTorrentFile class was added by @pyckle, so I'd suggest to first let him look into this when he has the time.

**Comment by pyckle** [comment]
@a8156268 - thanks for the bug report. Can you explain how this occurs/how to reproduce?

My understanding of how the code works is as follows:
`CompletableTorrentFile.countdown() `is only called from `LocalBitfield.markLocalPieceVerified()`. In `LocalBitfield.markLocalPieceVerified()`, an atomic (with locking) check is performed to check if this piece was completed already. `CompletableTorrentFile.countdown() `is then called if and only if the piece was not yet completed. This is sufficient to ensure that this AtomicLong is atomically decremented and the callback is not called until the file completes. If two chunks finish at the same time, the thread that calls the completed callback is non-deterministic, but we don't make any guarantees of what thread calls this callback, so this should be OK. 

I didn't implement piece indices it is more complex and less efficient. For large files with many (hundreds or thousands of pieces), we need to maintain this many bits for which pieces are complete, and after a piece finishes, check whether all pieces are completed.

**Comment by a8156268** [comment]
I'm sorrt, you are right.
I didn't notice thas `markLocalPieceVerified` return true only once for one piece.
