### ISSUE TITLE
Non-static torrents

### ISSUE THREAD

**Issue by just1689** [atomashpolskiy/bt#23]
Good day,

Not too sure what this is called but seeing as you have read the specifications for these protocols I'm sure you'll be able to tell.

May I ask if you have support for changing torrents? I'm sure there's a proper name for that. There's an app that uses torrent protocol to sync folders. I was thinking about this and I thought that maybe it changes the torrents contents and keep downloading them. Does bt support this?

**Comment by atomashpolskiy** [comment]
I only know about [BEP-44: Storing arbitrary data in the DHT](http://bittorrent.org/beps/bep_0044.html), which is by the way already implemented in [the8472/mldht](https://github.com/the8472/mldht), the library that I'm using for DHT. I don't know much about it though, and it would certainly be very challenging to incorporate this into Bt.

**Comment by just1689** [comment]
Keep rocking it dude. Thanks
