### ISSUE TITLE
Question : bt is not in published in Maven central ?

### ISSUE THREAD

**Issue by karuppiah7890** [atomashpolskiy/bt#3]
Looks like it is not yet published. The version 1.0
Please publish it.

Or how can I manually make the jar file out of the project ?

**Comment by karuppiah7890** [comment]
What is the metainfo ? Is it the torrent data ? It can't be magnet uri, since DHT is not even implemented

**Comment by atomashpolskiy** [comment]
Yes, it's content of a .torrent file

**Comment by karuppiah7890** [comment]
Okay!
