### ISSUE TITLE
not support windows？

### ISSUE THREAD

**Issue by Cuieney** [atomashpolskiy/bt#35]
Exception in thread "main" java.lang.RuntimeException: Failed to create terminal

**Comment by atomashpolskiy** [comment]
The only thing that is not currently supported on Windows is drawing the fancy GUI in CLI client. On Windows it should be run in headless mode by passing '-H' flag. Please see the [readme](https://github.com/atomashpolskiy/bt/blob/master/bt-cli/README.md) for more details.
