### ISSUE TITLE
Documentation on getting a PeerConnection instance?

### ISSUE THREAD

**Issue by kg6zvp** [atomashpolskiy/bt#39]
I've been looking through your code at everything related to direct connections to peers, but am having trouble piecing it together. I'm not using your library for BitTorrent per se, but am trying to look up peers in DHT by their ID and make a socket connection to them.

Ideally I'll stumble on code like the following:
```
CompletableFuture<PeerConnection> peerFut = runtime.getPeerconnectionById(peerID);
peerFut.get().postMessage(new Message("Hello"));
```

Is there any documentation or particular area of the source that you could point me to on establishing peer connections? I'd rather not re-write all of the hard work done by you and others required to punch holes in firewalls, etc.

**Comment by atomashpolskiy** [comment]
@kg6zvp , 

If you have the ID of a DHT node (this is different from BitTorrent's peer ID by the way and usually picked randomly for each session), you may use [NodeLookup task](https://github.com/the8472/mldht/blob/master/src/lbms/plugins/mldht/kad/tasks/NodeLookup.java) in mldht to get the node's socket address.

Then you need to decide, what protocol is going to be used to talk to the peer. If it's BitTorrent, then you'll need a torrent ID (info hash) for establishing a standard BitTorrent connection. To connect to a peer, use [bt.net.IPeerConnectionPool#requestConnection() method](https://github.com/atomashpolskiy/bt/blob/master/bt-core/src/main/java/bt/net/IPeerConnectionPool.java#L51).

**Comment by kg6zvp** [comment]
Thank you. That's a very helpful answer, particularly with all the links to code you included. :+1:

Is there any way of getting an instance of an interface that looks more like a standard socket through this process? (Since the use case isn't BitTorrent, I mean)

**Comment by atomashpolskiy** [comment]
Unfortunately, I'm afraid, that you'll need to look somewhere else for this. This project is in a very early stage and does not employ NAT traversal, as it requires a huge amount of effort to implement  and test and does not bring much to the table in the scope of BT (in my opinion). Regarding Bt, it relies on direct socket-to-socket TCP connections, no fancy stuff.
