### ISSUE TITLE
CLI not downloading

### ISSUE THREAD

**Issue by karuppiah7890** [atomashpolskiy/bt#4]
I actually tried used some code from bt-cli source code and there was no progress in download in my program. 

I was confused. So I tried the actual bt-cli from terminal using it's jar and it's giving the same result - no progress in download. No increase in download speed too.

Why is this happening ?

**Comment by atomashpolskiy** [comment]
Try checking `out.log` (should appear in the directory from which you ran bt-launcher.jar) for any exceptions. There are going to be quite a few `IOException`s, which you may safely ignore (it usually means that certain peers can't be reached).

**Comment by atomashpolskiy** [comment]
And feel free to post the log right here, I'll dig into it

**Comment by atomashpolskiy** [comment]
In fact it can be just because there are too few peers (without DHT you are limited to peers returned by the tracker and PEX). Try this torrent: http://releases.ubuntu.com/16.10/ubuntu-16.10-desktop-i386.iso.torrent. I'm able to download it with CLI client at a decent rate.

**Comment by karuppiah7890** [comment]
There were no exceptions in `out.log`. Weird. That torrent actually had good number of peers yesterday, when I downloaded the movie.

The ubuntu torrent is downloading fine.

**Comment by atomashpolskiy** [comment]
Nice to know! Btw, I've added some introductory docs yesterday, so you're welcome to take a look: http://atomashpolskiy.github.io/bt/intro/
