### ISSUE TITLE
Can't connect to peers

### ISSUE THREAD

**Issue by Elsrix** [atomashpolskiy/bt#41]
I used the instance code, even the magnet link is the same (I tried to use my own), but nothing happens

```java
public static void main(String[] args) {
        Config config = new Config() {
            @Override
            public int getNumOfHashingThreads() {
                return Runtime.getRuntime().availableProcessors() * 2;
            }
        };

        // enable bootstrapping from public routers
        Module dhtModule = new DHTModule(new DHTConfig() {
            @Override
            public boolean shouldUseRouterBootstrap() {
                return true;
            }
        });

        // get download directory
        Path targetDirectory = new File("~/Downloads").toPath();

        // create file system based backend for torrent data
        Storage storage = new FileSystemStorage(targetDirectory);

        // create client with a private runtime
        BtClient client = Bt.client()
                .config(config)
                .storage(storage)
                .magnet("magnet:?xt=urn:btih:af0d9aa01a9ae123a73802cfa58ccaf355eb19f1")
                .autoLoadModules()
                .module(dhtModule)
                .stopWhenDownloaded()
                .build();

        // launch
        client.startAsync().join();
    }
```

The conclusion showed 3 lines and it all ended

> 309 [main] INFO bt.runtime.BtRuntimeBuilder - Auto-loading module bt.tracker.http.HttpTrackerModule with default configuration
> 309 [main] INFO bt.runtime.BtRuntimeBuilder - Auto-loading module bt.peerexchange.PeerExchangeModule with default configuration
> 318 [main] INFO bt.runtime.BtRuntimeBuilder - Overriding auto-loaded module bt.dht.DHTModule
> 2482 [bt.net.pool.incoming-acceptor] INFO bt.net.PeerConnectionPool - Opening server channel for incoming connections @ /192.168.1.34:6891

What do I need to do to get it to work?

**Comment by atomashpolskiy** [comment]
I don't think that it's a real link, so there are probably no peers. Use your own link instead.

**Comment by Elsrix** [comment]
@atomashpolskiy I tried another link
magnet:?xt=urn:btih:711a6ac58f7288b9eaf5738923be8cef979ae868
the result is the same

Here is the torrent link from which the magnet reference is taken
http://x-tor.org/torrent/597415/udacha-logana_logan-lucky-2017-hdrip-l

Used the same magnet link in qbittorrent
![2017-11-16 15-29-36](https://user-images.githubusercontent.com/4102348/32881190-04b396e2-cae3-11e7-8d5f-5ca8bba5c4a5.png)

**Comment by madhawas1** [comment]
I am experiencing the same issue. With Magnet link, nothing happens.

**Comment by atomashpolskiy** [comment]
> magnet:?xt=urn:btih:711a6ac58f7288b9eaf5738923be8cef979ae868

Works for me both from CLI and with the code sample from the readme.

Are you behind a NAT router? Are you using the same port for Bt and qbittorrent? Bt uses 6891 and 49001 by default (BitTorrent and DHT servers respectively), which are probably closed on your router. qbittorrent uses UPnP to seamlessly setup port forwarding, but in case with Bt, you have to configure it manually.

Same goes for [yourip example issue](https://groups.google.com/forum/#!topic/bttorrent/bZcVrRGs6yA).

**Comment by madhawas1** [comment]
Can you give me sample code to set up UPnP with Bt, please?

**Comment by atomashpolskiy** [comment]
Sadly, there's no UPnP support in Bt for now. Though you may create a separate module with an adapter for one of the existing [Java UPnP libs](https://www.google.ru/search?q=java+upnp), and I'll be happy to receive a PR or provide a link to your repository in the README.

**Comment by atomashpolskiy** [comment]
@Elsrix , @madhawas1 , guys, by the way, are you using an Oracle JDK? If so, make sure to install JCE extension policy files: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html . Otherwise Bt won't be able to establish peer connections, which is exactly what we're seeing here.

**Comment by madhawas1** [comment]
@atomashpolskiy I'll try what you have suggested here, and let you know my results, thank you for your support.

**Comment by atomashpolskiy** [comment]
I presume that the issue has been solved, closing
