### ISSUE TITLE
Validation of bitfield message

### ISSUE THREAD

**Issue by ckovorodkin** [atomashpolskiy/bt#59]
`BitfieldHandler` doesn't validate received message.

https://wiki.theory.org/index.php/BitTorrentSpecification#bitfield:_.3Clen.3D0001.2BX.3E.3Cid.3D5.3E.3Cbitfield.3E

> A bitfield of the wrong length is considered an error. **Clients should drop the connection** if they receive bitfields that are not of the correct size, **or if the bitfield has any of the spare bits set.**

https://github.com/atomashpolskiy/bt/blob/a37ca29f3585d0b34a2fbeb532a92368432dae9c/bt-core/src/main/java/bt/protocol/handler/BitfieldHandler.java#L45-L58

**Comment by atomashpolskiy** [comment]
I definitely recall that the validation is done on some higher level

**Comment by atomashpolskiy** [comment]
Also, these handlers are supposed to perform only simple checks, i.e. that the message is well-formed and the values make sense given the context  (e.g. indices aren't negative). They don't know anything about a particular torrent session

**Comment by atomashpolskiy** [comment]
Checked, validation is done in `bt.torrent.BitfieldBasedStatistics#addBitfield`. If the length is invalid, an exception is raised, and connection is terminated.
Regarding spare bits, we don't care if these are set or not, as this does not affect anything
