### ISSUE TITLE
Incorrect behavior when the same peer participates in more than one torrent

### ISSUE THREAD

**Issue by ckovorodkin** [atomashpolskiy/bt#67]
Seams like library doesn't expect, that one peer can be connected to more than one torrent.

`PeerConnectionPool` is a singleton:
https://github.com/atomashpolskiy/bt/blob/77315dffded18989c82bb6c8756cb1f4ccf447a5/bt-core/src/main/java/bt/module/ServiceModule.java#L162
but mapping don't use TorrentId as a part of the key:
https://github.com/atomashpolskiy/bt/blob/77315dffded18989c82bb6c8756cb1f4ccf447a5/bt-core/src/main/java/bt/net/PeerConnectionPool.java#L201

**Comment by atomashpolskiy** [comment]
What do you mean by "one peer"? Peer in Bt is synonymous with a TCP socket, so there physically can't be two different connections. If some peer is serving more than one torrent, then the connection initiator will have to choose which _one_ torrent he wants to download from this peer.

**Comment by ckovorodkin** [comment]
> Peer in Bt is synonymous with a TCP socket, so there physically can't be two different connections.

Really? How about outgoing connections? https://github.com/atomashpolskiy/bt/pull/63#issuecomment-366218735

> If some peer is serving more than one torrent, then the connection initiator will have to choose which **one** torrent he wants to download from this peer.

Seams like BT have no 'connection initiator that choose which _one_ torrent he wants to download from this peer'  

But uTorrent can upload many-to-one and can download many torrents from one peer. It is quite common situation (in 2018).

**Comment by atomashpolskiy** [comment]
Yeah, seems like you're right. It looks like we will establish the connection and then immediately close it IF we're already downloading something from the same peer. Is it correct?

> But uTorrent can upload many-to-one

Seems like we can do this too) Need to support many-from-one though

**Comment by ckovorodkin** [comment]
> It looks like we will establish the connection and then immediately close it IF we're already downloading something from the same peer. Is it correct?

Yes, and use instead of closed connection another one that related to different torrent
https://github.com/atomashpolskiy/bt/blob/77315dffded18989c82bb6c8756cb1f4ccf447a5/bt-core/src/main/java/bt/net/ConnectionSource.java#L131-L137

It is dangerous malfunction.

The root problem in

> but mapping don't use TorrentId as a part of the key:
> https://github.com/atomashpolskiy/bt/blob/77315dffded18989c82bb6c8756cb1f4ccf447a5/bt-core/src/main/java/bt/net/PeerConnectionPool.java#L201
>

**Comment by atomashpolskiy** [comment]
Seems like we need to:
- change `bt.net.PeerConnectionPool#getConnection(Peer)` to `bt.net.PeerConnectionPool#getConnection(Peer, TorrentId)`
- update `bt.net.PeerConnectionPool#addConnectionIfAbsent` and everything down the line in this class to respect the connection's torrent ID

**Comment by ckovorodkin** [comment]
Please check this: `if (success) {` -> `if (removed != null) {`
https://github.com/atomashpolskiy/bt/commit/39d5d6709de0a694e71a5b460c1e8e7710ec5cd4#r27713125

**Comment by ckovorodkin** [comment]
Please review this: https://github.com/atomashpolskiy/bt/commit/39d5d6709de0a694e71a5b460c1e8e7710ec5cd4#r27713306 https://github.com/atomashpolskiy/bt/commit/39d5d6709de0a694e71a5b460c1e8e7710ec5cd4#r27713302


> `synchronized (modificationLock) {...}` -> `continue; // update in progress. We'll see it later.`
> 
> Let's do add/remove/cleanup work in dedicated methods.
>

**Comment by ckovorodkin** [comment]
> It is necessary to check the duplicate that occurs after the peer is reconnected.
> https://github.com/atomashpolskiy/bt/commit/39d5d6709de0a694e71a5b460c1e8e7710ec5cd4#r27773319
> https://github.com/atomashpolskiy/bt/commit/39d5d6709de0a694e71a5b460c1e8e7710ec5cd4#r27773326
> 

To prevent double (... triple, ets) message processing.
