### ISSUE TITLE
http://retracker.local/announce is ignored

### ISSUE THREAD

**Issue by ckovorodkin** [atomashpolskiy/bt#68]
> (announce key: [[http://tracker.example/ann], [http://retracker.local/announce]])

If announce key contains two tiers  and the first tier contains working tracker, then the current implementation of `MultiTracker ` will ignore (line # 133) the second tier. As a result, hi-speed local peers will not be discovered via `http://retracker.local/announce` in the ISP's local network. And LSD can't help in this case, because multicast packets will be suppressed in the ISP's local network.

https://github.com/atomashpolskiy/bt/blob/77315dffded18989c82bb6c8756cb1f4ccf447a5/bt-core/src/main/java/bt/tracker/MultiTracker.java#L114-L145

That use case isn't covered in http://www.bittorrent.org/beps/bep_0012.html
And is not taken into account in http://archive.is/GeZVd

PS

```
if (trackerTier.size() > 1 
        && i != 0 // ;-)
        ) {
    trackerTier.remove(i);
    trackerTier.add(0, currentTracker);
}
```

**Comment by atomashpolskiy** [comment]
I personally don't give a flying fuck whether `retracker.local` is used or not, because (a) it's unofficial and (b) it's not used by most ISPs anyway (especially in 2018).

> && i != 0 // ;-)

Good catch! :)

**Comment by ckovorodkin** [comment]
In other hand, that behaviour blocks statistic (upload/download/left) reporting to trackers in tailing tiers.

**Comment by atomashpolskiy** [comment]
In the first place, this behavior (announcing to multiple tiers at once or, alternatively, announcing to all trackers in one tier at once) violates BEP-12, which has these requirements for a good reason. I'm aware that some popular implementations (like libtorrent) make a compromise and provide options to enable this behavior, but we're not popular and therefore don't need to cater to obscure needs and idiosyncrasies of 1% of users.

**Comment by atomashpolskiy** [comment]
Applied the fix for removal/insertion of the first element in [61af03c18](https://github.com/atomashpolskiy/bt/commit/61af03c1812b98d525286919466afd4bd443cdb5). Thanks again!
