### ISSUE TITLE
Support for Java 7 and older

### ISSUE THREAD

**Issue by kebbbnnn** [atomashpolskiy/bt#7]
I'm trying to create a client app for this lib but it uses functions available only in java 8 and cannot run the app on pre android N since java 8 functions are only available for android N.

**Comment by atomashpolskiy** [comment]
Hi @kebbbnnn , thanks for trying out Bt. Like you said, Java 8 features are used in many places in the code, and this applies to APIs as well. I don't have the time to maintain a Java 6/7 compatible version of the library, so it's up to you whether you'd consider undertaking this task by yourself.

**Comment by kebbbnnn** [comment]
I actually thinking of making a port for java 6/7 too using rxjava. For the meantime i'll just test it out on android N devices. Btw, this is a great project, I'm excited for its future advancements.

**Comment by atomashpolskiy** [comment]
Thanks! Really looking forward to your feedback!

**Comment by bitsydarel** [comment]
Any update about this @kebbbnnn?

**Comment by 11hhlin1** [comment]
@kebbbnnn have you  change it to support for Java 7 and older?

**Comment by KORuL** [comment]
@kebbbnnn very interesting
