### ISSUE TITLE
running constantly to [bt.net.data-receiver] ERROR bt.net.DataReceivingLoop - Failed to process key

### ISSUE THREAD

**Issue by humanshield89** [atomashpolskiy/bt#77]
sorry if this is not where i should ask ,but i keep seeing that error when a simple exemple https://pastebin.com/CdKbnakr 

I was just wondering what does it mean ? i'm using open JDK as my JRE when running this code

**Comment by atomashpolskiy** [comment]
@humanshield89 , this is a perfect place to ask :)

This error usually means that there was a problem with the underlying I/O connection with the peer, hence in many cases it is expected and totally fine. It has the `ERROR` log level mainly due to Bt being in early stages of development and thus preferring debug-friendliness over log brevity.

I can look closer if you paste the full error message and stacktrace and describe the circumstances under which the error is happening and its frequency (i.e. does "constantly" mean "from time to time" or rather "all the time, spamming the log").

**Comment by humanshield89** [comment]
Thank you for the replay and the informative answer 
the full out put of the provided self running code exemple given before is [here ](https://pastebin.com/hr6bZkfa)
the full stack trace of the error thrown is (latest master linked as source for bt library on eclipce i'm not using maven ) 
```
[bt.net.data-receiver] ERROR bt.net.DataReceivingLoop - Failed to process key
java.lang.RuntimeException: Unexpected I/O error
	at bt.net.pipeline.SocketChannelHandler.read(SocketChannelHandler.java:83)
	at bt.net.pipeline.DefaultChannelPipeline$DefaultChannelHandlerContext.fireChannelReady(DefaultChannelPipeline.java:192)
	at bt.net.DataReceivingLoop.processKey(DataReceivingLoop.java:161)
	at bt.net.DataReceivingLoop.run(DataReceivingLoop.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at bt.net.pipeline.SocketChannelHandler.processInboundData(SocketChannelHandler.java:136)
	at bt.net.pipeline.SocketChannelHandler.read(SocketChannelHandler.java:80)
	... 6 more
```
I see it once in a while as you can see ,not all the time the code does it's job the torrent starts downloading (even tho slow ) peers are discovered and it's able to resume from where it left off out of the box 
The only concern I have is knowing what's making that error that's all (curiosity you can say ) plus the Log level 'ERROR' made me think maybe i'm messing something 

Other than that ,this is incredible ,thank you for all the hard work and effort you put into this project 
best of luck and have a good day

**Comment by atomashpolskiy** [comment]
Thank you for feedback, it's very valuable!

Considering the error, it's an java.io.EOFException, basically this means
that the remote peer closed the connection for some reason. In most cases
this is normal, so you may safely ignore it.

**Comment by humanshield89** [comment]
Thank you for the response that answers my question perfectly
