### ISSUE TITLE
Unexpected DHT error

### ISSUE THREAD

**Issue by gitzxon** [atomashpolskiy/bt#79]
hi，when i tried to run your sample code, i got this error info. Do you have any idea about this?

```
严重: Unexpected DHT error
java.io.IOException: /192.168.56.1 -> router.utorrent.com/82.221.103.244:6881 while attempting to send  Method:PING Type:REQ_MSG MessageID:0x3F62DF7EE9B5/?b�~��  
```

**Comment by atomashpolskiy** [comment]
Hi! Seems like the connection attempt for router.utorrent.com failed (maybe it was shut down or overloaded at the moment). This should not affect the operation of client in any significant way
