### ISSUE TITLE
UPNP for automatic port forwarding

### ISSUE THREAD

**Issue by OlegAndreych** [atomashpolskiy/bt#80]
Hi,
I'm willing to try to implement UPNP for bt. Is there any previous research about preferred libraries and implementation approach? Is there anything against https://github.com/4thline/cling in particular?

**Comment by atomashpolskiy** [comment]
Hi! Thank you for your interest!
I did not do any research. My only consideration would be that UPNP should work automatically without any additional configuration by the user, if the corresponding module is on the classpath. Not sure if it works that way though :)

**Comment by OlegAndreych** [comment]
Is there any module already implemented that way?

**Comment by OlegAndreych** [comment]
Ok, thanks, I'll look into it! )

**Comment by OlegAndreych** [comment]
Hey, GitHub! I didn't mean to show commits yet! =D

**Comment by OlegAndreych** [comment]
Is there any idea formatter configuration file I can apply to use autoformatting and avoid whole file changes?

**Comment by atomashpolskiy** [comment]
Не распарсил. Давай по-русски :)

**Comment by ckovorodkin** [comment]
Я так понял, что он хочет codestyle для IDEA :)
Я просто использовал опцию "переформатировать только измененные строки" и переформатирование не трогало лишнего. Использую IDEA от 15го года - там уже эта опция была.

**Comment by OlegAndreych** [comment]
@ckovorodkin, именно )
Ок, так и поступлю.
