### ISSUE TITLE
Receiving bt.net.DataReceivingLoop Failed to process key error while triggering the torrent 

### ISSUE THREAD

**Issue by architm** [atomashpolskiy/bt#86]
This is the stackTrace

> 2018-06-30 16:06:37.620[0;39m [31mERROR[0;39m [35m90434[0;39m [2m---[0;39m [2m[t.data-receiver][0;39m [36mbt.net.DataReceivingLoop                [0;39m [2m:[0;39m Failed to process key
> 
> java.lang.RuntimeException: Unexpected I/O error
> 	at bt.net.pipeline.SocketChannelHandler.read(SocketChannelHandler.java:83) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.net.pipeline.DefaultChannelPipeline$DefaultChannelHandlerContext.fireChannelReady(DefaultChannelPipeline.java:192) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.net.DataReceivingLoop.processKey(DataReceivingLoop.java:161) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.net.DataReceivingLoop.run(DataReceivingLoop.java:126) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
> 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
> Caused by: java.io.EOFException: null
> 	at bt.net.pipeline.SocketChannelHandler.processInboundData(SocketChannelHandler.java:136) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.net.pipeline.SocketChannelHandler.read(SocketChannelHandler.java:80) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	... 6 common frames omitted

Can you let me know why it is happening and implication of this in my application. The torrent is getting downloaded perfectly but want to root cause this issue before going forward.

**Comment by atomashpolskiy** [comment]
`EOFException` means that the remote peer closed the connection.

**Comment by architm** [comment]
Then is it good to log it as an error? It will try to find alternative peers then?

There some other errors i am getting

> [2m2018-06-30 16:15:34.267[0;39m [31mERROR[0;39m [35m90434[0;39m [2m---[0;39m [2m[ecutor-thread-1][0;39m [36mbt.torrent.TrackerAnnouncer             [0;39m [2m:[0;39m Failed to announce 'complete' event due to unexpected error during interaction with the tracker: MultiTracker{trackerTiers=[[UdpTracker{trackerUrl=http://zer0day.ch:1337/announce}], [UdpTracker{trackerUrl=http://tracker.coppersurfer.tk:6969/announce}], [UdpTracker{trackerUrl=http://tracker.openbittorrent.com:80/announce}], [UdpTracker{trackerUrl=http://glotorrents.pw:6969/announce}], [UdpTracker{trackerUrl=http://glotorrents.com:6969/announce}], [UdpTracker{trackerUrl=http://tracker.sktorrent.net:6969/announce}]]}
> 
> bt.BtException: All trackers failed; responses (in chrono order): [bt.tracker.TrackerResponse@51702634, bt.tracker.TrackerResponse@7518dbe9, bt.tracker.TrackerResponse@3b8be989, bt.tracker.TrackerResponse@27016a70, bt.tracker.TrackerResponse@7710b922, bt.tracker.TrackerResponse@44e4f3ba]
> 	at bt.tracker.MultiTracker$1.tryForAllTrackers(MultiTracker.java:145) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.tracker.MultiTracker$1.complete(MultiTracker.java:85) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.torrent.TrackerAnnouncer.lambda$complete$2(TrackerAnnouncer.java:98) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_92]
> 	at bt.torrent.TrackerAnnouncer.complete(TrackerAnnouncer.java:96) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_92]
> 	at bt.processor.torrent.ProcessTorrentStage.onCompleted(ProcessTorrentStage.java:97) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.torrent.ProcessTorrentStage.complete(ProcessTorrentStage.java:90) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.torrent.ProcessTorrentStage.doExecute(ProcessTorrentStage.java:66) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.torrent.ProcessTorrentStage.doExecute(ProcessTorrentStage.java:34) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.TerminateOnErrorProcessingStage.doExecute(TerminateOnErrorProcessingStage.java:38) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.RoutingProcessingStage.execute(RoutingProcessingStage.java:39) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.ChainProcessor.doExecute(ChainProcessor.java:112) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.ChainProcessor.executeStage(ChainProcessor.java:96) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.ChainProcessor.executeStage(ChainProcessor.java:98) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.ChainProcessor.executeStage(ChainProcessor.java:98) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.ChainProcessor.executeStage(ChainProcessor.java:98) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.ChainProcessor.executeStage(ChainProcessor.java:98) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at bt.processor.ChainProcessor.lambda$process$0(ChainProcessor.java:81) ~[bt-core-1.8-SNAPSHOT.jar:1.8-SNAPSHOT]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_92]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
> 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
> 


It seems that it is unable to announce completion of torrent. Am i missing something in setup?

**Comment by atomashpolskiy** [comment]
Nope, most probably trackers are unavailable for some reason

**Comment by architm** [comment]
Appreciate your quick response!

There are some other issues like the way i am calling library is like this
`
btClient.startAsync(state -> {
            if (state.getPiecesRemaining() == 0) {
                btClient.stop();
                isCompleted = true;
                System.out.println("Successfully completed torrent task!");
            } else {
                System.out.println("Waiting for the torrent download to complete!");
            }
        }, 1000);
`

How ca i get the list of files information that is getting downloaded from my application? Basically after download is complete i want to process those files.

**Comment by architm** [comment]
Never mind got the example.
