### ISSUE TITLE
How  to convert a few magnet links to torrents

### ISSUE THREAD

**Issue by rucliulingzhi** [atomashpolskiy/bt#88]
I want to write an api to convert magnet links to torrent files, but the bt-example says that it do not work on windows, so if I want to use this project to build a convert-util, what should I do? I just want torrent file and do not want the whole download.

**Comment by atomashpolskiy** [comment]
You may use [afterTorrentFetched](https://github.com/atomashpolskiy/bt/blob/master/bt-core/src/main/java/bt/TorrentClientBuilder.java#L209) builder method. You'll need to provide a consumer, that will stop the client and process the torrent metadata.
