### ISSUE TITLE
Failed to download bt-upnp.

### ISSUE THREAD

**Issue by YuntaoWei** [atomashpolskiy/bt#91]
Use the library this way：

``
<dependency>
    <groupId>com.github.atomashpolskiy</groupId>
    <artifactId>bt-core</artifactId>
    <version>${bt-version}</version>
</dependency>
<dependency>
    <groupId>com.github.atomashpolskiy</groupId>
    <artifactId>bt-http-tracker-client</artifactId>
    <version>${bt-version}</version>
</dependency>
<dependency>
    <groupId>com.github.atomashpolskiy</groupId>
    <artifactId>bt-dht</artifactId>
    <version>${bt-version}</version>
</dependency>
<dependency>
    <groupId>com.github.atomashpolskiy</groupId>
    <artifactId>bt-upnp</artifactId>
    <version>${bt-version}</version>
</dependency>
``

There is a problem about maven download:
Missing artifact com.github.atomashpolskiy:bt-upnp:jar:1.7

How to resolve it,thanks

**Comment by atomashpolskiy** [comment]
bt-upnp is present in 1.8-SNAPSHOT
