### ISSUE TITLE
How do I initially seed a file/folder?

### ISSUE THREAD

**Issue by asadsm** [atomashpolskiy/bt#92]
I've gone through the examples but I'm lost. What I want to do is create a torrent for a file/folder and start seeding it.

I create a torrent using an external tool after which I want to start seeding it so other machines can download it. Could you please point me in the right direction regarding this? Thanks

**Comment by atomashpolskiy** [comment]
@asadsm , please take a look at [this discussion](https://groups.google.com/forum/#!topic/bttorrent/iH7WJojuNyM) and [this message](https://groups.google.com/forum/#!msg/bttorrent/bZcVrRGs6yA/gaP36ejaAwAJ).

**Comment by atomashpolskiy** [comment]
Download speed is low because you're downloading the data via Internet. You should not use the public DHT infrastructure, i.e. do not set `shouldUseRouterBootstrap` to true. Also, move overridden `getBootstrapNodes` (which should return address of the seeder node) to the client's config (currently you're discovering your local seeder from the public DHT and get its external Internet address). Seeder node does not need bootstrap nodes at all because it itself is a bootstrap node for everyone else.

**Comment by asadsm** [comment]
Ah ok thanks...so I removed the public DHT, removed the override of `getBootstrapNodes ` from the seeder code and put it in the client code.

I'm running it now but it still seems very slow. I'm comparing it with seeder + client code I've written using Ttorrent which is also in Java.

**Comment by atomashpolskiy** [comment]
What do you mean by slow? Can you provide any numbers to compare?

I added an [example](https://github.com/atomashpolskiy/bt/tree/master/examples/src/main/java/datasharing) for your use case. It downloads a 10.5 GB file under 10 minutes, which means that the download rate is somewhere around 18 MB/s (via two connections, i.e. 9 MB/s per connection).

**Comment by asadsm** [comment]
It also didn't finish. Just stuck at 99.99%

```
[2018-10-03 09:32:50.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:32:51.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:32:52.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:32:53.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:32:54.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:32:55.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:32:56.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:32:57.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:32:58.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:32:59.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:33:00.452] Peers: 2; Downloaded: 99.99268898961836%
[2018-10-03 09:33:01.454] Peers: 2; Downloaded: 99.99268898961836%
```

**Comment by atomashpolskiy** [comment]
Yeah, Bt upload speed cap is determined by a number of configuration
parameters, and it's no surprise that with default settings you get more or
less the same rate as me. I was wondering more about ttorrent's default
rate and the difference with Bt (like 2x or 10x or higher).

**Comment by atomashpolskiy** [comment]
I rarely encounter 99% bug, but it happens sometimes. Not sure what causes
it.

**Comment by asadsm** [comment]
Got it. Thanks for your help!

**Comment by atomashpolskiy** [comment]
You're welcome. I'm not sure, but the issue with getting stuck at 99% may be related to #94 , which I've just fixed in master.

**Comment by vikulin** [comment]
How to create .torrent file from scratch if I intentionally don't want to use external app?
