### ISSUE TITLE
Duplicate Peers for multiple clients

### ISSUE THREAD

**Issue by luismance** [atomashpolskiy/bt#96]
I based my work on the PeerTracker example, Single runtime and multiple clients with magnet uri's. Using the onPeersDiscovered seems to be applied to all clients.
Sample :
torrent_1 - very popular torrent, many seeders
torrent_2 - new torrent, not so popular

I tried to run peer discovery on torrent_1 and torrent_2 on separate runtimes and torrent_1 gets like 200 peers and torrent_2 gets like 5. When I run torrent_1 and torrent_2 on a single runtime I seem to get 200 peers on both instead of the latter. Is it possible to get the onPeerDiscovered feature on the client.startAsync(state -> ) ? something like client.startAsync(state -> state.getPeersDiscovered) ?

**Comment by atomashpolskiy** [comment]
Not sure if I understand the problem. If you use `EventSource.onPeerDiscovered`, you get all peer discovered events for this runtime. Each event contains the torrent ID, so it's possible to distinguish between events for different torrents. Does this answer your question?

**Comment by luismance** [comment]
Yup, I missed that part, it's all good. Thanks for the response
